name: Scheduler

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  update-sponsors:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout with full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - name: Update sponsors
        run: pnpm run sponsorkit -f
        env:
          SPONSORKIT_GITHUB_TOKEN: ${{ secrets.SPONSORKIT_GITHUB_TOKEN }}
          SPONSORKIT_GITHUB_LOGIN: luoling8192

      - name: Commit and push sponsors changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: 'chore: update sponsors.svg [ci skip]'
          add: "sponsorkit/"
          pull: '--rebase --autostash'
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
